#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class EchoRequest; include ProtocolBuffers::Message; end
    class EchoResponse; include ProtocolBuffers::Message; end
    class PingRequest; include ProtocolBuffers::Message; end
    class PingResponse; include ProtocolBuffers::Message; end
    class HandleRequest; include ProtocolBuffers::Message; end

    class EchoRequest
      required :string, :phrase, 1
    end

    class EchoResponse
      required :string, :value, 1
    end

    class PingRequest
      required :int64, :time, 1
    end

    class PingResponse
      required :int64, :value, 1
    end

    class HandleRequest
    end

    class Echo
    include ProtocolBuffers::Service

      rpc :ask, "Ask", ::Entities::System::EchoRequest, ::Entities::System::EchoResponse
      rpc :ping, "Ping", ::Entities::System::PingRequest, ::Entities::System::PingResponse
      rpc :handle, "Handle", ::Entities::System::HandleRequest, ::Messages::Common::Mailbox
    end
  end
end
