#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class ServerHandleIncrementRequestMessage; include ProtocolBuffers::Message; end
    class ServerHandleIncrementResponseMessage; include ProtocolBuffers::Message; end

    class ServerHandleIncrementRequestMessage
    end

    class ServerHandleIncrementResponseMessage
      required :int32, :value, 1
    end

    class Handle
    include ProtocolBuffers::Service

      rpc :increment, "Increment", ::Entities::System::ServerHandleIncrementRequestMessage, ::Entities::System::ServerHandleIncrementResponseMessage
    end
  end
end
