#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class IncrementRequest; include ProtocolBuffers::Message; end
    class IncrementResponse; include ProtocolBuffers::Message; end

    class IncrementRequest
    end

    class IncrementResponse
      required :int64, :value, 1
    end

    class Handle
    include ProtocolBuffers::Service

      rpc :increment, "Increment", ::Entities::System::IncrementRequest, ::Entities::System::IncrementResponse
    end
  end
end
