#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class Cell; include ProtocolBuffers::Message; end
    class MatchState; include ProtocolBuffers::Message; end
    class ClientMatchMoveFromServerRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetMyIdRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetMyIdResponseMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetStateRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetStateResponseMessage; include ProtocolBuffers::Message; end
    class ServerMatchMakeMoveRequestMessage; include ProtocolBuffers::Message; end

    class Cell
      required :int32, :index, 1
      required :int32, :player, 2
      required :int32, :strength, 3
    end

    class MatchState
      repeated ::Entities::System::Cell, :cells, 1
    end

    class ClientMatchMoveFromServerRequestMessage
      required :string, :move, 1
    end

    class ServerMatchGetMyIdRequestMessage
    end

    class ServerMatchGetMyIdResponseMessage
      required :int32, :value, 1
    end

    class ServerMatchGetStateRequestMessage
    end

    class ServerMatchGetStateResponseMessage
      required ::Entities::System::MatchState, :value, 1
    end

    class ServerMatchMakeMoveRequestMessage
      required :string, :move, 1
    end

    class Match
    include ProtocolBuffers::Service

      client_rpc :move_from_server, "MoveFromServer", ::Entities::System::ClientMatchMoveFromServerRequestMessage, ::Phoenix::Messages::Void
      rpc :get_my_id, "GetMyId", ::Entities::System::ServerMatchGetMyIdRequestMessage, ::Entities::System::ServerMatchGetMyIdResponseMessage
      rpc :get_state, "GetState", ::Entities::System::ServerMatchGetStateRequestMessage, ::Entities::System::ServerMatchGetStateResponseMessage
      rpc :make_move, "MakeMove", ::Entities::System::ServerMatchMakeMoveRequestMessage, ::Phoenix::Messages::Void
    end
  end
end
