#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Auth
    # forward declarations
    class LoginRequest; include ProtocolBuffers::Message; end
    class LoginResponse; include ProtocolBuffers::Message; end

    class LoginRequest
      required :string, :email, 1
      required :string, :password, 2
    end

    class LoginResponse
      required ::Messages::Auth::User, :user, 1
      required ::Messages::Common::Mailbox, :account, 2
    end

    class Accounts
    include ProtocolBuffers::Service

      rpc :login, "Login", ::Entities::Auth::LoginRequest, ::Entities::Auth::LoginResponse
    end
  end
end
