#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    # forward declarations
    class ClientMatchMakerMatchReadyRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
    class ServerMatchMakerFindMatchRequestMessage; include ProtocolBuffers::Message; clear_fields!; end

    class ClientMatchMakerMatchReadyRequestMessage
      required ::Phoenix::Messages::Mailbox, :player, 1, :entity => "Entities::Game::Base::Player" 
    end

    class ServerMatchMakerFindMatchRequestMessage
      required ::Phoenix::Messages::Mailbox, :account, 1, :entity => "Entities::Auth::Account" 
    end

    class MatchMaker
    include ProtocolBuffers::Service
    clear_rpcs!

      client_rpc :match_ready, "MatchReady", ::Entities::Game::ClientMatchMakerMatchReadyRequestMessage, ::Phoenix::Messages::Void
      rpc :find_match, "FindMatch", ::Entities::Game::ServerMatchMakerFindMatchRequestMessage, ::Phoenix::Messages::Void
    end
  end
end
