#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    module Bots
      # forward declarations
      class AnarkiPropertiesMessage; include ProtocolBuffers::Message; clear_fields!; end

      class AnarkiPropertiesMessage
      end

      class Anarki
        include ProtocolBuffers::Service
        clear_rpcs!
        properties AnarkiPropertiesMessage
      end
    end
  end
end
