#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class ClientMatchMakerMatchReadyRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchMakerFindMatchRequestMessage; include ProtocolBuffers::Message; end

    class ClientMatchMakerMatchReadyRequestMessage
      required ::Phoenix::Messages::Mailbox, :match, 1, :entity => "Entities::System::Match" 
    end

    class ServerMatchMakerFindMatchRequestMessage
    end

    class MatchMaker
    include ProtocolBuffers::Service

      client_rpc :match_ready, "MatchReady", ::Entities::System::ClientMatchMakerMatchReadyRequestMessage, ::Phoenix::Messages::Void
      rpc :find_match, "FindMatch", ::Entities::System::ServerMatchMakerFindMatchRequestMessage, ::Phoenix::Messages::Void
    end
  end
end
