#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class Cell; include ProtocolBuffers::Message; end
    class MatchState; include ProtocolBuffers::Message; end
    class ClientMatchUpdateCellRequestMessage; include ProtocolBuffers::Message; end
    class ClientMatchLogMessageFromServerRequestMessage; include ProtocolBuffers::Message; end
    class ClientMatchErrorMessageFromServerRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetStateRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchGetStateResponseMessage; include ProtocolBuffers::Message; end
    class ServerMatchMakeMoveRequestMessage; include ProtocolBuffers::Message; end

    class Cell
      required :int32, :index, 1
      required :int32, :player, 2
      required :int32, :armySize, 3
    end

    class MatchState
      repeated ::Entities::System::Cell, :cells, 1
    end

    class ClientMatchUpdateCellRequestMessage
      required ::Entities::System::Cell, :cell, 1
    end

    class ClientMatchLogMessageFromServerRequestMessage
      required :string, :text, 1
    end

    class ClientMatchErrorMessageFromServerRequestMessage
      required :string, :text, 1
    end

    class ServerMatchGetStateRequestMessage
    end

    class ServerMatchGetStateResponseMessage
      required ::Entities::System::MatchState, :value, 1
    end

    class ServerMatchMakeMoveRequestMessage
      required :int32, :from, 1
      required :int32, :to, 2
    end

    class Match
    include ProtocolBuffers::Service

      client_rpc :update_cell, "UpdateCell", ::Entities::System::ClientMatchUpdateCellRequestMessage, ::Phoenix::Messages::Void
      client_rpc :log_message_from_server, "LogMessageFromServer", ::Entities::System::ClientMatchLogMessageFromServerRequestMessage, ::Phoenix::Messages::Void
      client_rpc :error_message_from_server, "ErrorMessageFromServer", ::Entities::System::ClientMatchErrorMessageFromServerRequestMessage, ::Phoenix::Messages::Void
      rpc :get_state, "GetState", ::Entities::System::ServerMatchGetStateRequestMessage, ::Entities::System::ServerMatchGetStateResponseMessage
      rpc :make_move, "MakeMove", ::Entities::System::ServerMatchMakeMoveRequestMessage, ::Phoenix::Messages::Void
    end
  end
end
