#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class ServerMatchmakerCreateMatchRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchmakerCreateMatchResponseMessage; include ProtocolBuffers::Message; end

    class ServerMatchmakerCreateMatchRequestMessage
    end

    class ServerMatchmakerCreateMatchResponseMessage
      required ::Phoenix::Messages::Mailbox, :value, 1, :entity => "Entities::System::Match" 
    end

    class Matchmaker
    include ProtocolBuffers::Service

      rpc :create_match, "CreateMatch", ::Entities::System::ServerMatchmakerCreateMatchRequestMessage, ::Entities::System::ServerMatchmakerCreateMatchResponseMessage
    end
  end
end
