#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class ServerMatchMakerCreateMatchRequestMessage; include ProtocolBuffers::Message; end
    class ServerMatchMakerCreateMatchResponseMessage; include ProtocolBuffers::Message; end

    class ServerMatchMakerCreateMatchRequestMessage
    end

    class ServerMatchMakerCreateMatchResponseMessage
      required ::Phoenix::Messages::Mailbox, :value, 1, :entity => "Entities::System::Match" 
    end

    class MatchMaker
    include ProtocolBuffers::Service

      rpc :create_match, "CreateMatch", ::Entities::System::ServerMatchMakerCreateMatchRequestMessage, ::Entities::System::ServerMatchMakerCreateMatchResponseMessage
    end
  end
end
