#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module System
    # forward declarations
    class Outer; include ProtocolBuffers::Message; end
    class ServerTestOutgoingRequestMessage; include ProtocolBuffers::Message; end
    class ServerTestOutgoingResponseMessage; include ProtocolBuffers::Message; end

    class Outer
      required ::Phoenix::Messages::Mailbox, :h, 1, :entity => "Entities::System::Handle" 
      repeated ::Phoenix::Messages::Mailbox, :hh, 2, :entity => "Entities::System::Handle" 
    end

    class ServerTestOutgoingRequestMessage
    end

    class ServerTestOutgoingResponseMessage
      required ::Entities::System::Outer, :value, 1
    end

    class Test
    include ProtocolBuffers::Service

      rpc :outgoing, "Outgoing", ::Entities::System::ServerTestOutgoingRequestMessage, ::Entities::System::ServerTestOutgoingResponseMessage
    end
  end
end
