#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Game
    module Base
      # forward declarations
      class Node; include ProtocolBuffers::Message; clear_fields!; end
      class Field; include ProtocolBuffers::Message; clear_fields!; end

      class Node
        required :int32, :from, 1
        required :int32, :to, 2
      end

      class Field
        repeated ::Messages::Game::Base::Cell, :cells, 1
        repeated ::Messages::Game::Base::Node, :nodes, 2
      end

    end
  end
end
