#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Game
    module Base
      # forward declarations
      class MatchState; include ProtocolBuffers::Message; clear_fields!; end

      class MatchState
        repeated ::Messages::Game::Base::Cell, :cells, 1
      end

    end
  end
end
