#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Auth
    # forward declarations
    class ServerAccountGetNameRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
    class ServerAccountGetNameResponseMessage; include ProtocolBuffers::Message; clear_fields!; end

    class ServerAccountGetNameRequestMessage
    end

    class ServerAccountGetNameResponseMessage
      required :string, :value, 1
    end

    class Account
    include ProtocolBuffers::Service
    clear_rpcs!

      rpc :get_name, "GetName", ::Entities::Auth::ServerAccountGetNameRequestMessage, ::Entities::Auth::ServerAccountGetNameResponseMessage
    end
  end
end
