#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Auth
    # forward declarations
    class AccountPropertiesMessage; include ProtocolBuffers::Message; clear_fields!; end

    class AccountPropertiesMessage
      optional :int32, :id, 1
      optional :string, :name, 2
    end

    class Account
      include ProtocolBuffers::Service
      clear_rpcs!
      properties AccountPropertiesMessage
    end
  end
end
