#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Auth
    # forward declarations
    class ServerLoginManagerLoginRequestMessage; include ProtocolBuffers::Message; end
    class ServerLoginManagerLoginResponseMessage; include ProtocolBuffers::Message; end

    class ServerLoginManagerLoginRequestMessage
      required ::Messages::Auth::Credentials, :credentials, 1
    end

    class ServerLoginManagerLoginResponseMessage
      required ::Phoenix::Messages::Mailbox, :value, 1, :entity => "Entities::Auth::Account" 
    end

    class LoginManager
    include ProtocolBuffers::Service

      rpc :login, "Login", ::Entities::Auth::ServerLoginManagerLoginRequestMessage, ::Entities::Auth::ServerLoginManagerLoginResponseMessage
    end
  end
end
