#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Game
    # forward declarations
    class MatchRequest; include ProtocolBuffers::Message; clear_fields!; end

    class MatchRequest
      required :int32, :match_type, 1
    end

  end
end
