#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Cell; include ProtocolBuffers::Message; clear_fields!; end

    class Cell
      required ::Messages::Geometry::Mesh, :mesh, 1
    end

  end
end
