#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Face; include ProtocolBuffers::Message; clear_fields!; end

    class Face
      repeated :int32, :indicies, 1
    end

  end
end
