#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Mesh; include ProtocolBuffers::Message; clear_fields!; end

    class Mesh
      repeated ::Messages::Geometry::Vertex, :vertices, 1
      repeated ::Messages::Geometry::Triangle, :triangles, 2
      repeated ::Messages::Geometry::Face, :faces, 3
    end

  end
end
