#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Vertex; include ProtocolBuffers::Message; clear_fields!; end
    class Triangle; include ProtocolBuffers::Message; clear_fields!; end
    class Mesh; include ProtocolBuffers::Message; clear_fields!; end

    class Vertex
      required :float, :x, 1
      required :float, :y, 2
      required :float, :z, 3
    end

    class Triangle
      required :int32, :index0, 1
      required :int32, :index1, 2
      required :int32, :index2, 3
    end

    class Mesh
      repeated ::Messages::Geometry::Vertex, :vertices, 1
      repeated ::Messages::Geometry::Triangle, :triangles, 2
    end

  end
end
