#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Triangle; include ProtocolBuffers::Message; clear_fields!; end

    class Triangle
      required :int32, :index0, 1
      required :int32, :index1, 2
      required :int32, :index2, 3
    end

  end
end
