#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Geometry
    # forward declarations
    class Vertex; include ProtocolBuffers::Message; clear_fields!; end

    class Vertex
      required :float, :x, 1
      required :float, :y, 2
      required :float, :z, 3
    end

  end
end
