#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    module Base
      # forward declarations
      class MatchPropertiesMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ClientMatchUpdateCellRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ClientMatchSwitchTurnRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ClientMatchSuccessfulAttackRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ClientMatchUnsuccessfulAttackRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerMatchGetStateRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerMatchGetStateResponseMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerMatchGetFieldGeometryRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerMatchGetFieldGeometryResponseMessage; include ProtocolBuffers::Message; clear_fields!; end

      class MatchPropertiesMessage
      end

      class ClientMatchUpdateCellRequestMessage
        required ::Messages::Game::Base::Cell, :cell, 1
      end

      class ClientMatchSwitchTurnRequestMessage
        required ::Phoenix::Messages::Mailbox, :player, 1, :entity => "Entities::Game::Base::Player" 
      end

      class ClientMatchSuccessfulAttackRequestMessage
        required ::Messages::Game::Base::Cell, :from_cell, 1
        required ::Messages::Game::Base::Cell, :to_cell, 2
      end

      class ClientMatchUnsuccessfulAttackRequestMessage
        required ::Messages::Game::Base::Cell, :from_cell, 1
        required ::Messages::Game::Base::Cell, :to_cell, 2
      end

      class ServerMatchGetStateRequestMessage
      end

      class ServerMatchGetStateResponseMessage
        required ::Messages::Game::Base::MatchState, :value, 1
      end

      class ServerMatchGetFieldGeometryRequestMessage
      end

      class ServerMatchGetFieldGeometryResponseMessage
        required ::Messages::Geometry::Field, :value, 1
      end

      class Match
        include ProtocolBuffers::Service
        clear_rpcs!
        properties MatchPropertiesMessage
        client_rpc :update_cell, "UpdateCell", ::Entities::Game::Base::ClientMatchUpdateCellRequestMessage, ::Phoenix::Messages::Void
        client_rpc :switch_turn, "SwitchTurn", ::Entities::Game::Base::ClientMatchSwitchTurnRequestMessage, ::Phoenix::Messages::Void
        client_rpc :successful_attack, "SuccessfulAttack", ::Entities::Game::Base::ClientMatchSuccessfulAttackRequestMessage, ::Phoenix::Messages::Void
        client_rpc :unsuccessful_attack, "UnsuccessfulAttack", ::Entities::Game::Base::ClientMatchUnsuccessfulAttackRequestMessage, ::Phoenix::Messages::Void
        rpc :get_state, "GetState", ::Entities::Game::Base::ServerMatchGetStateRequestMessage, ::Entities::Game::Base::ServerMatchGetStateResponseMessage
        rpc :get_field_geometry, "GetFieldGeometry", ::Entities::Game::Base::ServerMatchGetFieldGeometryRequestMessage, ::Entities::Game::Base::ServerMatchGetFieldGeometryResponseMessage
      end
    end
  end
end
