#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    module Base
      # forward declarations
      class MatchPropertiesMessage; include ProtocolBuffers::Message; clear_fields!; end

      class MatchPropertiesMessage
      end

      class Match
        include ProtocolBuffers::Service
        clear_rpcs!
        properties MatchPropertiesMessage
      end
    end
  end
end
