#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    module Base
      class Match
    include ProtocolBuffers::Service
    clear_rpcs!

      end
    end
  end
end
