#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Entities
  module Game
    module Base
      # forward declarations
      class PlayerPropertiesMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerPlayerMakeMoveRequestMessage; include ProtocolBuffers::Message; clear_fields!; end
      class ServerPlayerEndTurnRequestMessage; include ProtocolBuffers::Message; clear_fields!; end

      class PlayerPropertiesMessage
        optional :int32, :id, 1
      end

      class ServerPlayerMakeMoveRequestMessage
        required :int32, :from, 1
        required :int32, :to, 2
      end

      class ServerPlayerEndTurnRequestMessage
      end

      class Player
        include ProtocolBuffers::Service
        clear_rpcs!
        properties PlayerPropertiesMessage
        rpc :make_move, "MakeMove", ::Entities::Game::Base::ServerPlayerMakeMoveRequestMessage, ::Phoenix::Messages::Void
        rpc :end_turn, "EndTurn", ::Entities::Game::Base::ServerPlayerEndTurnRequestMessage, ::Phoenix::Messages::Void
      end
    end
  end
end
