#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Common
    # forward declarations
    class Mailbox; include ProtocolBuffers::Message; end

    class Mailbox
      required :string, :entity, 1
      required :string, :id, 2
    end

  end
end
