#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Auth
    # forward declarations
    class Credentials; include ProtocolBuffers::Message; end

    class Credentials
      required :int32, :id, 1
      required :string, :email, 2
      required :string, :password, 3
    end

  end
end
