#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Messages
  module Auth
    # forward declarations
    class Credential; include ProtocolBuffers::Message; clear_fields!; end

    class Credential
      required :int32, :id, 1
      required :string, :email, 2
      required :string, :password, 3
    end

  end
end
